apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: epay-ibmmq-source
  namespace: dev-kafka
  annotations:
    argocd.argoproj.io/sync-wave: '10'
    meta.helm.sh/release-name: epay-common
    meta.helm.sh/release-namespace: dev-epay-common
  labels:
    app.kubernetes.io/component: kafka-connector
    app.kubernetes.io/instance: epay-common
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: epay-ibmmq-source
    environment: dev
    strimzi.io/cluster: dev-kafka-connect
spec:
  class: com.ibm.eventstreams.connect.mqsource.MQSourceConnector
  tasksMax: 1
  config:
    mq.queue.manager: QM1
    mq.connection.name.list: "<MQ_HOST>(1414)"
    mq.channel.name: DEV.APP.SVRCONN
    mq.queue: DEV.QUEUE.1

    mq.user.name: ${file:/opt/kafka/external-configuration/mq-credentials/mq.username}
    mq.password: ${file:/opt/kafka/external-configuration/mq-credentials/mq.password}

    topic: mq-epay-events

    mq.message.body.format: string
    mq.record.builder: com.ibm.eventstreams.connect.mqsource.builders.DefaultRecordBuilder

    value.converter: org.apache.kafka.connect.converters.ByteArrayConverter
    value.converter.schemas.enable: "false"

    mq.poll.interval: "1000"
    mq.batch.size: "10"
