apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: neft-mq-sink-test
  namespace: dev-kafka
  labels:
    strimzi.io/cluster: dev-kafka-connect-mq-test
spec:
  class: com.ibm.eventstreams.connect.mqsink.MQSinkConnector
  tasksMax: 1
  config:
    topics: neft.processed.kafka.topic

    mq.queue.manager: SBI_NEFT
    mq.connection.name.list: "10.176.10.213(2001)"
    mq.channel.name: EPAY.TO.IPH
    mq.queue: SBI_NEFT_OUTWARD

    mq.message.body.format: string

    value.converter: org.apache.kafka.connect.converters.ByteArrayConverter
    value.converter.schemas.enable: "false"
